### ISSUE TITLE
Mocale.Exceptions.InitializationException error

### ISSUE THREAD

**Issue by gonultasmf** [Axemasta/Mocale#39]
![image](https://github.com/user-attachments/assets/a668e13c-bfde-4f86-b2f0-97e2ef4fc2a1)

Mocale.Exceptions.InitializationException: 'No cache provider has been registered. In the future there will be an in memory provider, for now please install and register the SQLite cache provider'

What is the reason for this error? How can I get rid of it?

**Comment by Axemasta** [comment]
Hey, thanks for the issue!

So currently you **need** to install the [mocale sqlite cache package](https://www.nuget.org/packages/Mocale.Cache.SQLite/) for the solution to function.

From the readme, you need to register it:
```csharp
var builder = MauiApp.CreateBuilder();
builder
    .UseMauiApp<App>()
    .UseMocale(mocale =>
    {
        mocale.WithConfiguration(config =>
            {
                ...
            })
            .UseSqliteCache(config =>
            {
                config.UpdateInterval = TimeSpan.FromDays(7);
            })
    })
```

The reason this throws is because there is no default caching implementation for mocale. I intend to ship a lightweight, in memory cache that will work without plugging in the sqlite package, since this package does create files within your app sandbox to manage the cache.

I would suggest looking at the mocale sample for a fully setup app using the libraries main features!

**Comment by gonultasmf** [comment]
Ok thanks, I solved this problem. But I have one more question. When the language is changed without refreshing the page during runtime, do the relevant values ​​change? Do you support such a feature? 
For example, as follows:
![LocalizationResourceManager](https://github.com/user-attachments/assets/f16ae32a-d30b-4884-990d-64d6084ed936)

**Comment by Axemasta** [comment]
Yes the localisations will update when you change the language immediately, no reloading required!

**Comment by gonultasmf** [comment]
Unfortunately, I have some problems. Let me share the codes:
```csharp
using Mocale.Abstractions;
using System.Globalization;

namespace Project2;

public partial class MainPage(ILocalizationManager localizationManager, ITranslatorManager translatorManager) : FmgLibContentPage
{
    public override void Build()
    {
        this
        .Content(
            new ScrollView()
            .Content(
                new Grid()
                .RowDefinitions(e => e.Star(90).Star(10))
                .Children(
                    (IView)new StackLayout()
                    .Spacing(25)
                    .Children(
                        new Label()
                        .Text("Hello, World!")
                        .FontSize(32)
                        .CenterHorizontal()
                        .SemanticHeadingLevel(SemanticHeadingLevel.Level1),

                        new Label()
                        .Text(translatorManager.Translate("LocalizationCurrentProviderIs"))
                        .FontSize(18)
                        .CenterHorizontal()
                        .SemanticDescription("Welcome to dot net Multi platform App U I")
                        .SemanticHeadingLevel(SemanticHeadingLevel.Level1),

                        new Label()
                        .Text("Current count: 0")
                        .FontSize(18)
                        .FontAttributes(Bold)
                        .CenterHorizontal(),

                        new Button()
                        .Text("Click me")
                        .CenterHorizontal()
                        .InvokeOnElement(btn => btn.Clicked += OnCounterClicked)
                        .SemanticHint("Counts the number of times you click"),

                        new Image()
                        .Source("dotnet_bot.png")
                        .WidthRequest(250)
                        .HeightRequest(310)
                        .CenterHorizontal()
                        .SemanticDescription("Cute dot net bot waving hi to you!")
                    )
                )
            )
        );
    }
    private async void OnCounterClicked(object? sender, EventArgs e)
  {
      var french = new CultureInfo("fr-FR");
      var english = new CultureInfo("en-GB");
      var newLang = localizationManager.CurrentCulture.Name == french.Name ? english : french;
      var changed = await localizationManager.SetCultureAsync(newLang);
  }
}

```

![image](https://github.com/user-attachments/assets/bd43567f-e956-47d2-ad59-460069a9a4d7)
![image](https://github.com/user-attachments/assets/9d1f4fc0-9192-48a6-b85d-2717dcbda378)
![image](https://github.com/user-attachments/assets/012b6a04-8cd8-4b25-8d26-1173dc1e3ae9)

```csharp
using Microsoft.Extensions.Logging;
using Mocale;
using Mocale.Cache.SQLite;
using System.Globalization;

namespace Project2;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UseMocale(mocale =>
            {
                mocale.WithConfiguration(config =>
                {
                    config.DefaultCulture = new CultureInfo("en-GB");
                    config.NotFoundSymbol = "?";
                    config.UseExternalProvider = false;
                    
                })
                .UseEmbeddedResources(config =>
                {
                    config.ResourcesPath = "Locales";
                    config.ResourcesAssembly = typeof(App).Assembly;
                    
                })
                .UseSqliteCache(config =>
                {
                    config.UpdateInterval = TimeSpan.FromDays(7);
                });
            })
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });

        builder.Logging.AddDebug();

        builder.Services
            .AddSingleton<App>()
            .AddSingleton<AppShell>()
            .AddScoped<MainPage>();

        return builder.Build();
    }
}

```
![image](https://github.com/user-attachments/assets/c4dcf2d5-ff39-4501-b76d-af8113a48048)
When I click on the button and follow it with Debug mode, the codes are running but there is no change on the UI side. And if you noticed, it did not bring the relevant key value.

**Comment by Axemasta** [comment]
Ok the reason for this is because you are not actually using the localizations in your page UI. 

If you take a look at the samples you can see the xaml using a [markup extension](https://github.com/Axemasta/Mocale/blob/1c85e702d1e46f80b34a8d1ee449a0c9c53e5e1b/samples/Mocale.Samples/Pages/IntroductionPage.xaml#L46) to set the localization:
```xml
<Label Text="{mocale:Localize Key={x:Static keys:TranslationKeys.MocaleDescription}}" />
```

This is not the same as calling `translatorManager.Translate("...");` because the markup extension sets a [binding](https://github.com/Axemasta/Mocale/blob/1c85e702d1e46f80b34a8d1ee449a0c9c53e5e1b/src/Mocale/Extensions/LocalizeExtension.cs#L37) that listens to the `ITranslatorManager` and updates when its language is changed. The reason your code isn't updating is because you are setting the text value as a string, not a binding.

In previous versions the code first ui would be totally unsupported. In the newest release there is a new api for setting localisations in code, [`SetTranslation("");`](https://github.com/Axemasta/Mocale/blob/1c85e702d1e46f80b34a8d1ee449a0c9c53e5e1b/src/Mocale/Extensions/BindableObjectExtension.cs#L4).

Unfortunately I do not recognise the syntax for the way you are building your ui. Is there a specific UI framework you are using here (comet, fluent ui etc?). I tried dropping your code into my project and rider was showing errors so I can't provide a tested solution yet. Either you will need to use the `SetTranslation` method, however it is a binding extension and is generally used like this:
```csharp
var label = new Label();
label.SetTranslation(Label.TextProperty, "MyKey");
```

So i dont think this fixes your issue immediately. Please can you provide a link to a sample repo on github so I can pull the codebase and look on my machine? I can add whatever api you need that works with the fluent ui syntax so you can get going!

**Comment by gonultasmf** [comment]
Hello,

I published a class that provides Fluent Methods because I don't like using XAML in MAUI. With the FmgLib.MauiMarkup library, I offer C# Markup.
Project repo: https://github.com/gonultasmf/MocaleMauiApp
FmgLib.MauiMarkup Repo: https://github.com/FmgLib/FmgLib.MauiMarkup
FmgLib.MauiMarkup Documents: https://fmgyazilim.com/en/fmglibmauimarkup/

**Comment by Axemasta** [comment]
Ok since you are using a custom UI library this is obviously not directly supported. I'm only providing support for XAML and C#, my advise it to create an extension for FmgLib that will set the localization:

```csharp
public static T Localisation<T>(this T self,
        string translationKey)
        where T : Label
    {
        self.SetTranslation(Label.TextProperty, translationKey);
        return self;
    }
```

You would need to do this for all controls you wish to use, although it will mainly be Labels & Editors so shouldn't be too resource intensive.

Long term there should be a compabitility library for any UI framework that doesn't plug directly into Maui, FmgLib.Compatibility.Mocale. I would happily add that compatibility library as I want to be able to support as many approached to building maui apps as possible!

**Comment by gonultasmf** [comment]
I'm already providing this structure with FmgLib.MauiMarkup. When I examined the structure of the SetTranslation method, I noticed that Binding operations are applied. 
![image](https://github.com/user-attachments/assets/f828c63c-10b1-4724-9644-b99a51cce29b)

We can do these with FmgLib.MauiMarkup like this:
```csharp
new Label()
.Text(e => e.Path("[LocalizationCurrentProviderIs]").Source(MocaleLocator.TranslatorManager).BindingMode(BindingMode.OneWay))
.FontSize(18)
.CenterHorizontal()
.SemanticDescription("Welcome to dot net Multi platform App U I")
.SemanticHeadingLevel(SemanticHeadingLevel.Level1)
```

I'm thinking the first issue we should look at is: why isn't the key's value coming through at all? It prints the value like this: ?LocalizationCurrentProviderIs? What could be the reason? If this issue is resolved, the language switching problem will be fixed.
![image](https://github.com/user-attachments/assets/7f27cce0-407c-48dc-b9f2-fa5fcb7dc1e1)

**Comment by gonultasmf** [comment]
Can you successfully implement your system in a MAUI application developed with CommunityToolkit.Maui.Markup?

If your answer is yes, could you provide a link to a sample repository?
If your answer is no, it would be great if you could adjust your system to be compatible with a MAUI application developed with CommunityToolkit.Maui.Markup.

**Comment by Axemasta** [comment]
Thanks for providing the sample app, the binding code you used is working. We can see that because the not found symbol is being applied at runtime.

Mocale uses the `ILogger` to output diagnostics, we can see the following logs:
```
Mocale.Providers.EmbeddedResourceProvider: Warning: No assembly resources found with prefix: Project2.Resources.Locales
Mocale.Managers.LocalizationManager: Warning: Unable to load translations for culture: en-GB
Mocale.Managers.TranslatorManager: Warning: Resource key not found 'LocalizationCurrentProviderIs'
```

Looks like the locale files have not been setup correctly:

```diff
<ItemGroup>
	 <AdditionalFiles Include="Resources\Locales\*.json" />
+	 <EmbeddedResource Include="Resources\Locales\*.json" />
</ItemGroup>
```

Since you've chosen to use embedded resources, you need to mark the locales folder as such. The additional files is also correct, this is used by the source generator to create the static string key definitions. I hope to one day add a custom file type to the project to make this easier to manage but for now we need both the `EmbeddedResource` and the `AdditionalFilesTag`

https://github.com/user-attachments/assets/f6e184ed-480b-4256-9c0b-d021faecb165

**Comment by Axemasta** [comment]
Your binding stuff does work inline (i like the fmg library by the way, it looks nice to use!) although I would recommend moving it into some extensions to make easier to manage / look cleaner:

```csharp
public static class LabelExtensions
{
    public static T Localize<T>(this T self, string translationKey) where T : Label
    {
        self.SetTranslation(Label.TextProperty, translationKey);
        return self;
    }
}

new Label()
.Localize(TranslationKeys.LocalizationCurrentProviderIs)
.FontSize(18)
.CenterHorizontal()
.SemanticDescription("Welcome to dot net Multi platform App U I")
.SemanticHeadingLevel(SemanticHeadingLevel.Level1),
```

I will look into the community toolkit markup library and see what if there are any wrappers I can add on my side to make building this stuff easier for c# only projects!

**Comment by gonultasmf** [comment]
Thank you very much for your support :)

**Comment by Axemasta** [comment]
No worries, I'm happy to see people using the library! :)

**Comment by gonultasmf** [comment]
I starred the library to support it. I'm glad you liked FmgLib.MauiMarkup too :)
